"""create chunk 1 core identity and lead entities

Revision ID: 2952be1b6e48
Revises: 95ef3c40f71e
Create Date: 2026-09-29 00:18:06.102400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2952be1b6e48'
down_revision: Union[str, Sequence[str], None] = '95ef3c40f71e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
