"""create chunk 2 pipeline events campaigns and messaging entities

Revision ID: 6ca9439b9034
Revises: fc4b5a915350
Create Date: 2026-09-29 00:31:49.122531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca9439b9034'
down_revision: Union[str, Sequence[str], None] = 'fc4b5a915350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
