"""create chunk 3 conversations appointments agent runs and decisions entities

Revision ID: a947b3c28733
Revises: bfc88ad31b6c
Create Date: 2026-09-29 00:44:32.250665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a947b3c28733'
down_revision: Union[str, Sequence[str], None] = 'bfc88ad31b6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('extra_metadata', sa.JSON(), nullable=True))
    op.drop_column('conversations', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('conversations', 'extra_metadata')
    # ### end Alembic commands ###
